### ISSUE TITLE
2nd+ streams lead to errors that can cause some players to not work.

### ISSUE THREAD

**Issue by noideaman** [m1k1o/go-transcode#22]
The first person to get the stream works, video plays back fine. 
any one after will get errors that cause the video to freeze or the player to refuse to play

See the attached video

https://user-images.githubusercontent.com/39884745/141701010-e01b7afc-674c-4485-b930-6abff0671df8.mp4

This happens on lan and over hls proxy.
I have tried changing the type of audio as well happens to both aac and mp3
Using the latest git docker build as well.

**Comment by m1k1o** [comment]
Thanks for reporting. My first thought is issue #20. Could you please enable debug logs and see what messages are reported?

In Yaml:

```yaml
# allow debug outputs
debug: true
```

**Comment by noideaman** [comment]
[error.log](https://github.com/m1k1o/go-transcode/files/7543794/error.log)
got the debug output.

**Comment by m1k1o** [comment]
I can't seem to reproduce it with my source and players (vlc & ffplay). All five clients are running smoothly.

![image](https://user-images.githubusercontent.com/7534274/142462292-407d2800-b31d-4344-b7b8-a7e1adc36d05.png)

**Comment by noideaman** [comment]
Can i get you a box on my network to test on?
it will be windows due to parsec. can msg ya on matrix

**Comment by m1k1o** [comment]
Sure. That would help.

**Comment by noideaman** [comment]
got you ready to go, but cant seem to msg you.

**Comment by m1k1o** [comment]
I cant seem to message you too. It just keeps loading.

**Comment by noideaman** [comment]
I have federation enabled. it is a docker container, just updated it seems to be having issues no clue as to why

**Comment by noideaman** [comment]
Also i am begingin to think this is more of how the hdhomerun gives the stream out. having the issue with just running ffmpeg out side of go-transocde

**Comment by noideaman** [comment]
been testing some more have had more luck getting less errors with these flags over the hls muxer
``` -f ssegment \
 -segment_list v760.m3u8 \
 -segment_list_type hls \
 -segment_wrap 4 \
 -segment_list_size 4 \
 -segment_list_flags +live \
 -segment_time 2 v760-%03d.ts```

**Comment by noideaman** [comment]
been messing around more. get issues even with those,
Seems to be how hdhomerun hands off the stream. 
Only truly stable way is (so far) is to play the video in obs and stream over nginx-rtmp.

**Comment by m1k1o** [comment]
I would like to look into it and find cause of the problem. Can you give me access to a test stream? Or at least record some portion of it and upload it please here (zipped, so that github cannot try any retranscoding).
