### ISSUE TITLE
Error on probe

### ISSUE THREAD

**Issue by rudnypc** [m1k1o/go-transcode#24]
Error:
4:47PM ERR unable to load metadata error="unable probe video for keyframes: strconv.ParseFloat: parsing \"\": invalid syntax"

When I do the ffprobe in terminal I get this result:
`ffprobe -v error -skip_frame nokey -show_entries frame=pkt_pts_time,side_data_list -show_entries format=duration -show_entries stream=duration,width,height -select_streams v -of json MYVIDEO.mkv`
```
{
    "frames": [
        {
            "side_data_list": [
                {

                },
                {

                }
            ]
        },
        {
            "pkt_pts_time": "0.000000"
        },
        {
            "pkt_pts_time": "2.002000"
        },
        {
            "pkt_pts_time": "3.712000"
        },
        {
            "pkt_pts_time": "8.592000"
        },
.............................
```
Could be the side_data_list?

**Comment by m1k1o** [comment]
This should fix the issue. `strconv.ParseFloat: parsing "": invalid syntax` so it tried to parse empty string as number.
