### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by rezaalimorady** [m1k1o/go-transcode#28]
Hello
could you share some of usage example for this module?
TNX

**Comment by rezaalimorady** [comment]
for example i have a mp4 file in /media directory
`4f9c8335-90b1-4551-a59d-7534bc553057_360.mp4`

and i want the index file -> with this url 
http://localhost:8080/vod/4f9c8335-90b1-4551-a59d-7534bc553057_360.mp4/index.m3u8
and it returns : 
`500 unable to preload metadata`

docker-compose logs:
```
go-transcode    | 12:08PM WRN unable to preload metadata error="unable probe media for metadata: exit status 1" module=hlsvod
go-transcode    | 12:08PM DBG request complete (500) module=http req={"agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36","id":"b7e509d9545f/KM6lrEb4VP-000020","method":"GET","proto":"HTTP/1.1","remote":"172.18.0.1:35092","scheme":"http","uri":"http://localhost:8080/vod/4f9c8335-90b1-4551-a59d-7534bc553057_360.mp4/index.m3u8"} res={"bytes":31,"elapsed":22.711615,"status":500,"time":"Sun, 05 Dec 2021 12:08:20 UTC"}
```
config.yaml file :
```
# allow debug outputs
debug: true

# mount debug pprof endpoint at /debug/pprof/
pprof: true

# bind server to IP:PORT (use :8888 for all connections)
bind: localhost:8080

# serve static files from this directory (optional)
static: /var/www/html

# TODO: issue #4
proxy: true

# For live streaming
streams:
  cam: rtmp://localhost/live/cam
  ch1_hd: http://localhost:9981/stream/channelid/85
  ch2_hd: http://localhost:9981/stream/channelid/43

# For static files
vod:
  # Source, where are static files, that will be transcoded
  media-dir: ./media
  # Temporary transcode output directory, if empty, default tmp folder will be used
  transcode-dir: ./transcode
  # Available video profiles
  video-profiles:
    360p:
      width: 640 # px
      height: 360 # px
      bitrate: 800 # kbps
    540p:
      width: 960
      height: 540
      bitrate: 1800
    720p:
      width: 1280
      height: 720
      bitrate: 2800
    1080p:
      width: 1920
      height: 1080
      bitrate: 5000
  # Use video keyframes as existing reference for chunks split
  # Using this might cause long probing times in order to get
  # all keyframes - therefore they should be cached
  video-keyframes: false
  # Single audio profile used
  audio-profile:
    bitrate: 192 # kbps
  # If cache is enabled
  cache: true
  # If dir is empty, cache will be stored in the same directory as media source
  # If not empty, cache files will be saved to specified directory
  cache-dir: ./cache
  # Use custom ffmpeg & ffprobe binary paths
  ffmpeg-binary: ffmpeg
  ffprobe-binary: ffmpeg

# For proxying HLS streams
hls-proxy:
  my_server: http://localhost:9981
```

what should i do for index.m3u8 file for a mp4?

**Comment by rezaalimorady** [comment]
Any document for this module?

**Comment by m1k1o** [comment]
Yes, adding usage examples for all modules would be needed.

Quick question, do you have ffmpeg installed? If it cannot preload metdata, it might be because of missing ffmpeg. Or do you use docker image?

And you say your files are in `/media` but in config it is `./media`. Is that expected?

**Comment by rezaalimorady** [comment]
Thanks
ffmpeg installed before

![image](https://user-images.githubusercontent.com/60624937/144746832-423957be-c9c3-4099-a43d-4502267678b7.png)

i used your docker-compose for build
I think its about my `media-dir: /media`

i use `/media` directory for videos. what should i put in `config.yaml` -> `media-dir: -----`

**Comment by m1k1o** [comment]
If you use `/media`, then `media-dir: /media` should be  the correct entry.

**Comment by rezaalimorady** [comment]
![image](https://user-images.githubusercontent.com/60624937/144747192-b31e3886-6df9-40d8-8d49-e26fd1b8e4d1.png)

still problem exist

**Comment by m1k1o** [comment]
Your config file is mounted as volume to docker, right? And after changing it you restarted the container and it does not work, correct?

**Comment by rezaalimorady** [comment]
absolutely yes

![image](https://user-images.githubusercontent.com/60624937/144747490-410ec664-22ca-4619-9658-8ba3c7608c79.png)

and this is my `/media` directory.

![image](https://user-images.githubusercontent.com/60624937/144747543-c839e20c-8d46-4ccd-873e-24dae34be85f.png)

**Comment by m1k1o** [comment]
Can you try to execute `ffprobe` on that file inside container, to rule out all permissions issues?

Something like this:

```bash
docker-compose exec go-trancode ffprobe /media/4f9c8335-90b1-4551-a59d-7534bc553057_360.mp4
```

**Comment by rezaalimorady** [comment]
could not find the file from inside docker

![image](https://user-images.githubusercontent.com/60624937/144747740-b5fe1444-f6ec-4d99-be2c-3cbe2166cbbf.png)

from outside container it works

![image](https://user-images.githubusercontent.com/60624937/144747801-7224d7c2-b029-4f1d-8a07-c116f73c5f87.png)

**Comment by m1k1o** [comment]
Is it mounted correctly? With `- ./media:/media`.

```yaml
version: "3"

services:
  go-transcode:
    build: . # path to go-transcode repository
    container_name: go-transcode
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./media:/media
    command: serve -d
```

**Comment by rezaalimorady** [comment]
`ffprobe`  fixed
when i correct my `docker-compose`

![image](https://user-images.githubusercontent.com/60624937/144748197-34071e90-c53c-44ce-a1bd-f5515fdfcea5.png)

but the URL -> http://localhost:8080/vod/4f9c8335-90b1-4551-a59d-7534bc553057_360.mp4/index.m3u8
still dosn't return anything

`docker-compose logs -f `

```
go-transcode    | 1:17PM WRN unable to preload metadata error="unable probe media for metadata: exit status 1" module=hlsvod
go-transcode    | 1:17PM DBG request complete (500) module=http req={"agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36","id":"d03e06e9d058/03MFNWvPjp-000002","method":"GET","proto":"HTTP/1.1","remote":"172.18.0.1:56356","scheme":"http","uri":"http://localhost:8080/vod/4f9c8335-90b1-4551-a59d-7534bc553057_360.mp4/index.m3u8"} res={"bytes":31,"elapsed":22.090266,"status":500,"time":"Sun, 05 Dec 2021 13:17:36 UTC"}

```

**Comment by rezaalimorady** [comment]
![image](https://user-images.githubusercontent.com/60624937/144748322-af37f262-1db0-4af0-bfc9-f680384c2ce0.png)

**Comment by m1k1o** [comment]
Just noticed! I have mistake in readme:

```
  ffmpeg-binary: ffmpeg
  ffprobe-binary: ffmpeg
```

`ffprobe-binary` should be `ffprobe`, but it is `ffmpeg`. That is why `show_format` is unrecognized. Gonna fix that, thanks!

**Comment by rezaalimorady** [comment]
No problem dear.
i change it 
but still same problem
![image](https://user-images.githubusercontent.com/60624937/144748666-e381e77a-93c6-4aaf-aec8-99e2ac34dcac.png)

its into docker image:
![image](https://user-images.githubusercontent.com/60624937/144748686-012e4319-bc0e-455b-8f74-e0fef8453ba7.png)

**Comment by m1k1o** [comment]
It looks like, error persists and ffmpeg is still called (because of the `show_format` error). Could you try to recreate your container, to be usre changes were applied?

**Comment by rezaalimorady** [comment]
completly remove it
![image](https://user-images.githubusercontent.com/60624937/144749067-c423ec8b-48b6-4c4f-94e4-b982ac4fc8e7.png)

config inside docker image
![image](https://user-images.githubusercontent.com/60624937/144749085-fd0a2f35-960e-41db-ba8c-0bd096977a04.png)

and `ffprobe` error not show 
there is another error :)
![image](https://user-images.githubusercontent.com/60624937/144749148-c8a53ed1-c592-48aa-9fce-e1695f1f8601.png)

**Comment by m1k1o** [comment]
Oh okey. I see. Your cache dir does not exist. I just noticed that might be error and fixed in https://github.com/m1k1o/go-transcode/commit/c26cba02f9f846736afd1980ff8eddfa404e8a05.

If you want to keep your cache along with the files, you can remove `cache-dir: ./bin/cache` this line. Or specify directory, that exists (mount it in docker compose).

**Comment by m1k1o** [comment]
Added usage examples.

**Comment by rezaalimorady** [comment]
Thanks bro.
I pulled last changes and problem fixed.
but this url -> http://localhost:8080/vod/4f9c8335-90b1-4551-a59d-7534bc553057_360.mp4/index.m3u8
not retun completly manifest file
![image](https://user-images.githubusercontent.com/60624937/144798379-3529747c-2802-4d22-9610-a2c52cccfb3b.png)

**Comment by rezaalimorady** [comment]
Thanks for adding usage example
please add usage example for profile or multi probile/bitrate manifest.
and how can add new profile or change current profile

**Comment by m1k1o** [comment]
If the master playlist is empty, that can mean, your video resolution is lower than the lowest profile. You can try to get the profile directly. E.g. `http://localhost:8080/vod/4f9c8335-90b1-4551-a59d-7534bc553057_360.mp4/360p.m3u8` and it should work.

I consider adding the lowest profile all the time, because it should never return empty playlist.

**Comment by rezaalimorady** [comment]
Thanks
It play when i using to get all of this urls
http://localhost:8080/vod/4f9c8335-90b1-4551-a59d-7534bc553057_360.mp4/360p.m3u8
http://localhost:8080/vod/4f9c8335-90b1-4551-a59d-7534bc553057_360.mp4/720p.m3u8
http://localhost:8080/vod/4f9c8335-90b1-4551-a59d-7534bc553057_360.mp4/1080p.m3u8

but i need the master file.
how could i get the master file?

**Comment by m1k1o** [comment]
What is the resolution of the video? There is also no point in upscaling, if it is not 1080p. I can though leave at least the lowest one in all cases.

**Comment by rezaalimorady** [comment]
i use a 1080 video -> http://localhost:8080/vod/17bb20ab-4028-4e2f-acb4-619e4d79c8da_1080.mp4/index.m3u8

the output is like :
```
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=945000,RESOLUTION=640x360,NAME=360p
360p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1995000,RESOLUTION=960x540,NAME=540p
540p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3045000,RESOLUTION=1280x720,NAME=720p
720p.m3u8
```

why 1080 profile not in index file?
how could i config these.

**Comment by rezaalimorady** [comment]
and how aout subtitles?
how could i add subtitle track?

**Comment by rezaalimorady** [comment]
I hope your team write powerfull document for this module.
really needed

**Comment by m1k1o** [comment]
> why 1080 profile not in index file?

It looks like a bug, I'll look into this. It should be visible.

> I hope your team write powerful document for this module.

My team consist of only me right now. Contributors are welcomed. This module is experimental now and thanks to the people who use it and give me feedback, like you, I can catch lots of bugs and make it better for everyone.

**Comment by rezaalimorady** [comment]
Thank you for your patient response :)
Hopefully being best.
