### ISSUE TITLE
static file access

### ISSUE THREAD

**Issue by noideaman** [m1k1o/go-transcode#33]
Trying to test static files. the config file is pointed to /media
has full access to the folder mounted

`mpv http://IPADDR:8888/vod/TV/SouthPark/Specials/South_Park_-_S00E44_-_South_Park-_Post_COVID-_The_Return_of_COVID_WEBDL-1080p.mkv/index.m3u8`

get an error 500 and the output with debug on on go-transcode

```
12:46AM INF fetching metadata module=hlsvod submodule=manager
2021/12/28 00:46:13 Unrecognized option 'show_format'.
Error splitting the argument list: Option not found

12:46AM WRN unable to preload metadata error="unable probe media for metadata: exit status 1" module=hlsvod
12:46AM DBG request complete (500) module=http req={"agent":"libmpv","id":"go-transcode/NeOacMNoCW-000004","method":"GET","proto":"HTTP/1.1","remote":"192.168.6.133:1082","scheme":"http","uri":"http://IPADDR:8888/vod/TV/SouthPark/Specials/South_Park_-_S00E44_-_South_Park-_Post_COVID-_The_Return_of_COVID_WEBDL-1080p.mkv/index.m3u8"} res={"bytes":31,"elapsed":11.91186,"status":500,"time":"Tue, 28 Dec 2021 00:46:13 UTC"}
12:46AM DBG request complete (405) module=http req={"agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36","id":"go-transcode/NeOacMNoCW-000005","method":"HEAD","proto":"HTTP/1.1","remote":"192.168.6.133:1083","scheme":"http","uri":"http://IPADDR:8888/vod/TV/SouthPark/Specials/South_Park_-_S00E44_-_South_Park-_Post_COVID-_The_Return_of_COVID_WEBDL-1080p.mkv/index.m3u8"} res={"bytes":0,"elapsed":0.013375,"status":405,"time":"Tue, 28 Dec 2021 00:46:14 UTC"}
12:46AM INF fetching metadata module=hlsvod submodule=manager
2021/12/28 00:46:14 Unrecognized option 'show_format'.
Error splitting the argument list: Option not found

12:46AM WRN unable to preload metadata error="unable probe media for metadata: exit status 1" module=hlsvod
12:46AM DBG request complete (500) module=http req={"agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36","id":"go-transcode/NeOacMNoCW-000006","method":"GET","proto":"HTTP/1.1","remote":"192.168.6.133:1084","scheme":"http","uri":"http://IPADDR:8888/vod/TV/SouthPark/Specials/South_Park_-_S00E44_-_South_Park-_Post_COVID-_The_Return_of_COVID_WEBDL-1080p.mkv/index.m3u8"} res={"bytes":31,"elapsed":11.783193,"status":500,"time":"Tue, 28 Dec 2021 00:46:14 UTC"}
```

**Comment by m1k1o** [comment]
It looks like you are calling ffmpeg instead of ffprobe:

```
Unrecognized option 'show_format'.
Error splitting the argument list: Option not found
```

It was mistakenly introduced in default config, found in https://github.com/m1k1o/go-transcode/issues/28#issuecomment-986229677 and fixed in d0590d5ffd5e2ec88ac2a1c290cb1f10d3051287

**Comment by noideaman** [comment]
awesome. seems to be working. except in vlc, audio is not trans coding properly, ffplay and mpv work fine

**Comment by noideaman** [comment]
Working on a intel QSV version as i dont have a usable nvidia gpu for decoding/encoding in containers, but an 11th gen intel cpu.
will have to compile ffmpeg to include qsv for h264/h265 will make a pull request when that docker file is done and testing is working
Hopefuly this will fix my transocding issues on my h265 static library

**Comment by noideaman** [comment]
what sh file under profiles is being used for vods?

**Comment by noideaman** [comment]
Ok i think the main issue is now (dosent matter if i used software or hardware for decoding) is how hlsvod/transcode.go (or somewhere else) works. it seems to wait too long between ffmpeg commands to create the new .ts files

**Comment by m1k1o** [comment]
Maybe adjusting config values would solve it. In [V1](https://github.com/m1k1o/go-transcode/pull/30) I want to have all settings accessible through config, so multiple values can be tried without need of recompiling.

**Comment by noideaman** [comment]
Cool will try, are the values in the transcode.go file?

**Comment by m1k1o** [comment]
Here: https://github.com/m1k1o/go-transcode/blob/deceb3820f52e11f1c0e8b2c7295b3bb257dda39/hlsvod/manager.go#L60-L63

And explained here: https://github.com/m1k1o/go-transcode/issues/23#issuecomment-983854966
