### ISSUE TITLE
Unrecognized option 'hls_wrap' from ffmpeg

### ISSUE THREAD

**Issue by pranksta02** [m1k1o/go-transcode#35]
Hi there,

Just made a fresh build and getting the below error when trying to do any copy or transcode stream, logging into the container and running the same command gives the below response:

bash-5.2# /app/profiles/hls/copy.sh url=http://pathtostream      
Unrecognized option 'hls_wrap'.
Error splitting the argument list: Option not found

ffmpeg version:
bash-5.2# ffmpeg
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers

**Comment by m1k1o** [comment]
Hi. This issue is known. That ffmpeg argument has been replaced in ffmpeg v5. Somebody said they will do PR but it was forgotten about.

**Comment by pranksta02** [comment]
Thanks for the quick response, do you happen to know what the replacement argument is?

**Comment by m1k1o** [comment]
I found the links:

https://stackoverflow.com/questions/27227175/ffmpeg-http-live-streaming-remove-old-segments
https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/d96ebc5ef88024869de06bcf92b2ad99b01d47e3

`hls_wrap` has been deprecated in favor of `hls_list_size` and `hls_flags delete_segments`. We already have the newer ones, so it just needs to be removed.
