### ISSUE TITLE
reverse proxying

### ISSUE THREAD

**Issue by klahaha** [m1k1o/go-transcode#4]
[from here](https://github.com/m1k1o/go-transcode/pull/3#issuecomment-926760416)

Server.Proxy setting should enable/disable trusting of X-Forwarded-For headers

**Comment by m1k1o** [comment]
Could be implemented as HTTP middleware.

**Comment by klahaha** [comment]
i'm curious why. go-transcode doesn't filter by IP so why X-Forwarded-For ?

**Comment by m1k1o** [comment]
Just for transparency and auditing, to have real user's IP in logs.
