### ISSUE TITLE
Question:  mp4 proxy

### ISSUE THREAD

**Issue by stevyn81** [m1k1o/go-transcode#51]
Hello, testing now for VOD project and everything is working great, amazing project!  Thank you very much for an excellent transcoder. I have been researching for days on how to do this and your work is a great solution.

I see the HLS proxy, is it possible to proxy MP4?

Pull from a remote server https://remote-server.com/move.mp4

**Comment by m1k1o** [comment]
Hello, thanks!

It depends on what you want to do with the file and whether its live stream or VOD. 

Assuming its VOD - its just a file then:
- If you want to proxy the file itself, that can be done by any proxy, e.g. nginx, traefik...
- If you want to first segment the file to the HLS you can do it either once (using ffmpeg) and save the output then serve as static page.
- If you want to transcode it on demand to HLS and then proxy, you can to it with this project and then simply take the HLS output and proxy that.

Assuming its live:
- You might want to ingest it to some live streaming server, e.g. [mediamtx](https://github.com/bluenviron/mediamtx).
- You could restream it to HLS using [hls-restream](https://github.com/m1k1o/hls-restream/).

**Comment by stevyn81** [comment]
Hello,  I will "If you want to transcode it on demand to HLS and then proxy, you can to it with this project and then simply take the HLS output and proxy that."  working on this now, thanks much!
