### ISSUE TITLE
panic: specify at least one VOD video profile

### ISSUE THREAD

**Issue by metal450** [m1k1o/go-transcode#52]
So excited to find this - it looks like exactly what I was looking for :)

However, trying to get it up & running in Docker, I'm getting stuck with `panic: specify at least one VOD video profile` (even when using the sample hlsvod config.yaml, which I believe does list 4 video profiles). Here's the complete A-Z steps I'm following:

```
git clone https://github.com/m1k1o/go-transcode
cd go-transcode
cp docs/examples/hlsvod/config.yaml config.yaml
cp docs/examples/hlsvod/docker-compose.yaml docker-compose.yaml
mkdir media
# (copy a few vids into the media dir)
docker-compose up
```
The result: 

![2024-06-12 21 50 30](https://github.com/m1k1o/go-transcode/assets/1877409/5d13d9bb-4309-4bd5-89a9-9ca6a7c0aa4a)

Given that I'm using the docs/examples/hlsvod/config.yaml file, should it not work with the setup above?

Thanks in advance

**Comment by m1k1o** [comment]
The first line says that it does not use config file. What is weird, since you have it there.

**Comment by metal450** [comment]
Hmm, interesting, it behaves like the above on Windows (using Docker Toolbox) but if I run it on a Linux host it actually works. Good enough for me!

Thanks for the quick reply :)
