### ISSUE TITLE
Auto-detect hardware acceleration

### ISSUE THREAD

**Issue by klahaha** [m1k1o/go-transcode#6]
We can detect hardware acceleration in program. Using ffmpeg cli

```
ffmpeg -init_hw_device list 2> /dev/null
Supported hardware device types:
vdpau
vaapi
qsv
drm
opencl
```

then no need for profiles config just print what profiles are used on startup

what outputs the command with nvidia proprietaire driver?

**Comment by m1k1o** [comment]
For nvidia it prints:

```
Supported hardware device types:
vdpau
cuda
vaapi
```

So it's `cuda`.

**Comment by klahaha** [comment]
now in repo via #3
